### PR TITLE
Replace p.Name.Equals with String.Equals. Fixes issue #23.

### PR DESCRIPTION
**Pull request by GeirGrusom**

### CODE REVIEW

**Comment by simondebaecke** [comment]
Sorry but someone could tell the difference between these two comparisons methods ? O_o

Thx !

**Comment by fubar-coder** [comment]
I merged it manually, Thank you for your pull request.

**Comment by fubar-coder** [comment]
Hi,

the difference is, that - in the old source - the Equals method is an instance method, while the string.Equals is a static method. The instance method cannot be called when Name is null, but the static method gracefully handles null strings.

Von meinem Windows Phone gesendet
________________________________
Von: Simon Debaecke<mailto:notifications@github.com>
Gesendet: ‎05.‎05.‎2015 17:10
An: FubarDevelopment/restsharp.portable<mailto:restsharp.portable@noreply.github.com>
Betreff: Re: [restsharp.portable] Replace p.Name.Equals with String.Equals. Fixes issue #23. (#26)


Sorry but someone could tell the difference between these two comparisons methods ? O_o

Thx !

**Comment by simondebaecke** [comment]
Thank for the follow up ! (even though I have come to realize it shortly after asking my question, that's why I deleted it. ;))

**Pull request closed without merging**
